export const COMPONENT_NAMES = {
  0: { key: "face", label: "Face" },
  1: { key: "mask", label: "Mask" },
  2: { key: "hair", label: "Hair" },
  3: { key: "torso", label: "Torso" },
  4: { key: "legs", label: "Legs" },
  5: { key: "bag", label: "Bag/Backpack" },
  6: { key: "shoes", label: "Shoes" },
  7: { key: "accessories", label: "Accessories" },
  8: { key: "undershirt", label: "Undershirt" },
  9: { key: "armor", label: "Armor" },
  10: { key: "decals", label: "Decals" },
  11: { key: "tops", label: "Tops" },
};

export const HEAD_OVERLAYS = {
  0: { key: "blemishes", label: "Blemishes", overlayId: 0, defaultColorType: 0 },
  1: { key: "facialhair", label: "Facial Hair", overlayId: 1, defaultColorType: 1 },
  2: { key: "eyebrows", label: "Eyebrows", overlayId: 2, defaultColorType: 1 },
  3: { key: "ageing", label: "Ageing", overlayId: 3, defaultColorType: 0 },
  4: { key: "makeup", label: "Makeup", overlayId: 4, defaultColorType: 1 },
  5: { key: "blush", label: "Blush", overlayId: 5, defaultColorType: 2 },
  6: { key: "complexion", label: "Complexion", overlayId: 6, defaultColorType: 0 },
  7: { key: "sundamage", label: "Sun Damage", overlayId: 7, defaultColorType: 0 },
  8: { key: "lipstick", label: "Lipstick", overlayId: 8, defaultColorType: 2 },
  9: { key: "moles", label: "Moles", overlayId: 9, defaultColorType: 0 },
  10: { key: "chesthair", label: "Chest Hair", overlayId: 10, defaultColorType: 1 },
  11: { key: "bodyblemishes", label: "Body Blemishes", overlayId: 11, defaultColorType: 0 },
  12: { key: "addbodyblemishes", label: "Additional Body Blemishes", overlayId: 12, defaultColorType: 0 },
};

export const FACE_FEATURES = {
  0: { label: "Nose Width" },
  1: { label: "Nose Peak Height" },
  2: { label: "Nose Peak Low" },
  3: { label: "Nose Bone High" },
  4: { label: "Nose Bone Low" },
  5: { label: "Nose Tip" },
  6: { label: "Nose Bone Twist" },
  7: { label: "Eyebrow Height" },
  8: { label: "Eyebrow Thickness" },
  9: { label: "Eyebrow Angle" },
  10: { label: "Eye Squint" },
  11: { label: "Cheeks Height" },
  12: { label: "Cheeks Bone High" },
  13: { label: "Cheeks Bone Width" },
  14: { label: "Cheeks Bone Lowering" },
  15: { label: "Lips Thickness" },
  16: { label: "Lips Size" },
  17: { label: "Chin Height" },
  18: { label: "Chin Bone Low" },
  19: { label: "Chin Bone Length" },
};
